### ISSUE TITLE
Explore using Jupyter notebooks for data exploration using GitHub pages

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/jupyter-ghpages-test#1]
### Overview
As a part of the data analysis, we are looking to be able to use notebooks integrated into a site hosted on GitHub Pages.
### Action Items

- [x] Research use of interactive notebooks for website
- [x] Test on GH pages

### Resources/Instructions
Demo Jupyter Lite hosted on our GH Pages [here](https://hackforla.github.io/jupyter-ghpages-test/lab/index.html)

**Comment by chelseyklein** [comment]
## Working Solution
Went with a [Jupyterlite](https://jupyterlite.readthedocs.io/en/latest/) install and it can be demoed [here](https://hackforla.github.io/jupyter-ghpages-test/lab/index.html). It looks like it can be further customized, but I like that we could spin up a notebook and explore data without having to do any additional installs.

Limitations: 

- Jupyterlite cannot import from https links. It should not be a problem if we store csv files inside the repo in the data directory. I did test importing csv files into the notebook from there in the browser and it worked great.
- We will need to find a solution that allows for the querying (with joins) of csv files...from the browser.
- Another option would be to set up a database - if we can [host one cheaply](https://www.websiteplanet.com/blog/best-mysql-hosting/) (will research)

## Other Solutions Explored
Mercury looks like a promising solution: https://github.com/mljar/mercury
- Could not use this as it is based on Django and cannot be hosted on GH pages

nbinteract - https://www.nbinteract.com/tutorial/tutorial_github_setup.html
- Tried installing this and it looked promising but it isn't maintained and there are a lot of dependency issues.
- I liked this as a way to embed parts of a notebook into a web page with interactivity. I imagine it would take quite a bit of work to get the codebase up to date.

**Comment by chelseybeck** [comment]
So does nbinteract - https://www.nbinteract.com/tutorial/tutorial_github_setup.html

**Comment by chelseyklein** [comment]
@ExperimentsInHonesty would [this](https://hackforla.github.io/jupyter-ghpages-test/lab/index.html) work? It's basically as if we are hosting notebooks via JupyterLab on GH Pages.
